"""empty message

Revision ID: 445fff858a0a
Revises: 2eb860a18afd
Create Date: 2022-08-18 12:01:41.481048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445fff858a0a'
down_revision = '2eb860a18afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.create_foreign_key('contact_user_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_constraint('contact_user_fkey', type_='foreignkey')

    # ### end Alembic commands ###
