"""empty message

Revision ID: 980f33b8e432
Revises: 9e0e179b016f
Create Date: 2022-08-19 12:17:08.806499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980f33b8e432'
down_revision = '9e0e179b016f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('street_address', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=10), nullable=False))
        batch_op.drop_column('name')
        batch_op.drop_column('address')
        batch_op.drop_column('number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.VARCHAR(length=15), nullable=False))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('zip_code')
        batch_op.drop_column('country')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('street_address')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
